# Generated by Django 6.0.3 on 2026-04-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institutions', models.JSONField(default=list)),
                ('department', models.CharField(max_length=255)),
                ('academic_position', models.CharField(max_length=100)),
                ('research_interests', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'researchers',
            },
        ),
    ]
