# Generated by Django 6.0.3 on 2026-05-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='academic_position',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='h_index',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='keywords',
        ),
    ]
