# Generated by Django 6.0.3 on 2026-03-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.researcher')),
            ],
            options={
                'db_table': 'reviewers',
            },
        ),
    ]
