# Generated by Django 6.0.3 on 2026-05-03 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0002_remove_paper_created_at_remove_paper_research_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_status', models.CharField(default='Pending', max_length=50)),
                ('paper_score', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('paper_id', models.ForeignKey(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
                ('reviewer_id', models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_assignment',
            },
        ),
    ]
