# Generated by Django 6.0.3 on 2026-04-03 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_status', models.CharField(default='Pending', max_length=50)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('paper', models.ForeignKey(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
                ('reviewer', models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_assignment',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.researcher')),
            ],
            options={
                'db_table': 'reviewers',
            },
        ),
    ]
