# Generated by Django 6.0.2 on 2026-02-12 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('subject_area', models.JSONField(default=list)),
                ('pdf_url', models.URLField()),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.CreateModel(
            name='PaperMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_names', models.JSONField(default=list)),
                ('paper_affiliations', models.JSONField(default=list)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='papers.paper')),
            ],
            options={
                'db_table': 'paper_metadata',
            },
        ),
    ]
