# Generated by Django 6.0.3 on 2026-03-22 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('research_domain', models.JSONField(default=list)),
                ('pdf_url', models.URLField()),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.CreateModel(
            name='PaperMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_names', models.JSONField(default=list)),
                ('paper_affiliations', models.JSONField(default=list)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='papers.paper')),
            ],
            options={
                'db_table': 'paper_metadata',
            },
        ),
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='papers.paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_reviews',
                'unique_together': {('paper', 'reviewer')},
            },
        ),
    ]
