# Generated by Django 6.0.3 on 2026-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='research_domain',
        ),
        migrations.AddField(
            model_name='paper',
            name='author_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_affiliations',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PaperMetadata',
        ),
    ]
