# Generated by Django 6.0.3 on 2026-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paperreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreview',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
    ]
