# Generated by Django 6.0.3 on 2026-03-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_paperreview_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='subject_area',
            new_name='research_domain',
        ),
    ]
